### ISSUE TITLE
list of pages to grab the links

### ISSUE THREAD

**Issue by ghost** [ihebski/LinksF1nd3r#2]
@ihebski how to use a list of pages and grab the links of all of them?

**Comment by ihebski** [comment]
List of pages are currently not supported (single page by default), however, Linux bash can do it for you if you have the pages offline 
`grep -o '<a href=".*">' *.html | sed 's/\(<a href="\|\">\)//g' > link.txt;`

PS : The code will be fixed soon.
Thank you for reporting the issue.

**Comment by ghost** [comment]
What about if I dont have them offline.
What I have is a .txt file containing a list of addresses, inwhich I want to scrape each one for links within.
