### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ghost** [ihebski/LinksF1nd3r#3]
@ihebski 
When running `python linksF1nd3r.py` I get error:

```
$ python linksF1nd3r.py www.imdb.com
  File "linksF1nd3r.py", line 28
    print "[!] "+str(err)
               ^
SyntaxError: invalid syntax
```

**Comment by ihebski** [comment]
The code is running under python2.7

You can change the code to :  ` print "[!] ",str(err)`

We will upgrade the tool to support python3 ,soon.
Thank you.

**Comment by deepseek** [comment]
ok i install py27

**Comment by ghost** [comment]
@ihebski merge the py3 pull request
