### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lamia787** [ihebski/LinksF1nd3r#8]
Used this once b4 and it was great 
This time around keep getting this error

python linksF1nd3r.py

/data/data/com.termux/files/home/LinksF1nd3r/linksF1nd3r.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp                                                    [!] module 'html5lib.treebuilders' has no attribute '_base'

Help

**Comment by ihebski** [comment]
Thanks for reporting that, the code uses an old b4 library which is deprecated,therefore we have to refractor the code to support the newer version.

If you need to keep using the old version please reinstall the packages with an older versions. it should keeps the code working properly.

**Comment by lamia787** [comment]
Thanks for getting back to me. Can u plz elaborate what i need to install
please im only a noob lol

Thanks

**Comment by lamia787** [comment]
Please help how do i fix this problem so i cam still use urgently needed. Insructions would really help me

Thnx

**Comment by ihebski** [comment]
You can use curl and grep to get the JS or any other extension files as following : 

`curl example.com | egrep -iE '(\.js|\.png)'`

Example to get the `.php` file extensions you can change the grep as following : 
`curl example.com | egrep -iE '(\.js|\.png|\.php)'`

**Comment by lamia787** [comment]
Oh ok i'm actually trying to locate all the html url links to magazines
that a certain company emails out to members any idea on the exact command
i should use please??

Any help i could get would be amazing

**Comment by ihebski** [comment]
* Extract HTTP URLS
`grep -i http | grep -shoP 'http.*?[" >]' file.txt > http-urls.txt`

* Extract email address
`grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" file.txt`

**Comment by lamia787** [comment]
Ur the best

Do I need to add the ip or the email address/s in there at all?
